package de.watchmywatch.repository.storage;

import de.watchmywatch.model.OrderManagment.Payment;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.Optional;

@Controller // Identifies Class as Controller
@RequestMapping(path="/api") // URL's start with /demo (after Application path)
public class PaymentController {
    @Autowired // This means to get the bean called PaymentRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    public PaymentRepository paymentRepository;


    @PostMapping(path="/payment") // Map ONLY POST Requests
    public @ResponseBody String addNewPayment (Payment payment) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        // TODO: Testing should be done in a different file/class ...
        // Payment testPayment = new Payment();

        paymentRepository.save(payment);
        return "Saved";
    }


    @GetMapping(path="/payments")
    public @ResponseBody Iterable<Payment> getAllPayments() {
        // This returns a JSON or XML with the users
        return paymentRepository.findAll();
    }

    @GetMapping(value="/payment/{paymentId}")
    public @ResponseBody Optional<Payment> getOnePayment(@PathVariable Integer  paymentId) {
        // This returns a JSON or XML with the one payment

        return paymentRepository.findById(paymentId);
    }
}
