package de.watchmywatch.repository.core;


import de.watchmywatch.model.AccountManagment.Customer;
import de.watchmywatch.repository.core.CustomerRepository;
import org.springframework.beans.factory.annotation.Autowired;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.Optional;


@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)

public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CustomerRepository customerRepository;


    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewCustomer (@RequestParam Customer customer) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        customerRepository.save(customer);
        return "Saved";
    }




    @GetMapping(path="/all")
    public @ResponseBody Iterable<Customer> getAllUsers() {
        // This returns a JSON or XML with the users
        return customerRepository.findAll();
    }

    @GetMapping(value="/{userId}")
    public @ResponseBody Optional<Customer> getOneUser(@PathVariable Integer  CutomerId) {
        // This returns a JSON or XML with the one user

        return customerRepository.findById(CutomerId);
    }





}




