package de.watchmywatch.repository.core;


import de.watchmywatch.model.Helper.Address;
import org.springframework.beans.factory.annotation.Autowired;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;


import java.util.Optional;


@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)

public class MainController {
    @Autowired // This means to get the bean called CustomerRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    public CustomerRepository customerRepository;


    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewCustomer () {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        Address address = new Address("Lilo-Herrmann-Straße 2", "Erfurt", "Thüringen", "99086");
        //Customer  customer = new Customer("anton.bespalov@fh-erfurt.de", address, "01716181447", "Anton", "Bespalov", new Date(1998, Calendar.SEPTEMBER, 23));
        address.setId(1);
        customerRepository.save(address);
        return "Saved";
    }


    @GetMapping(path="/all")
    public @ResponseBody Iterable<Address> getAllUsers() {
        // This returns a JSON or XML with the users
        return customerRepository.findAll();
    }

    @GetMapping(value="/{customerId}")
    public @ResponseBody Optional<Address> getOneUser(@PathVariable Integer  customerId) {
        // This returns a JSON or XML with the one user

        return customerRepository.findById(customerId);
    }





}




